services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd-music-downloader
    ports:
      - "5030:5030"
      - "50300:50300"
    volumes:
      - ./slskd.yml:/app/slskd.yml:ro
      - ./downloads:/app/downloads
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
